import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { musicService } from "@/services/musicService";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Sparkles, Music, Wand2 } from "lucide-react";
import { useNavigate } from "react-router-dom";

export function AiPlaylistDialog({ open, onOpenChange }) {
    const [prompt, setPrompt] = useState("");
    const [loading, setLoading] = useState(false);
    const [step, setStep] = useState("input"); // input, analyzing, creating, done
    const [result, setResult] = useState(null);
    const { toast } = useToast();
    const navigate = useNavigate();

    const handleGenerate = async () => {
        if (!prompt.trim()) return;

        setLoading(true);
        setStep("analyzing");

        try {
            // 1. Analyze Prompt
            const aiResponse = await musicService.getAiSuggestion(prompt);
            setResult(aiResponse);

            // 2. Fetch Matching Songs (only by mood, not genre)
            setStep("fetching");
            const songsResponse = await musicService.getAllSongs({
                moodId: aiResponse.moodId,
                pageSize: 20
            });

            const songs = songsResponse.songs || [];
            if (songs.length === 0) {
                toast({
                    title: "No songs found",
                    description: `We couldn't find any songs matching ${aiResponse.suggestedName} criteria.`,
                    variant: "destructive"
                });
                setLoading(false);
                setStep("input");
                return;
            }

            // 3. Create Playlist
            setStep("creating");
            const playlist = await musicService.createPlaylist(
                `✨ ${aiResponse.suggestedName}`,
                `${aiResponse.suggestedDescription} (Generated by AI based on: "${prompt}")`,
                false // private by default
            );

            // 4. Add Songs to Playlist
            // doing sequentially to avoid race conditions or backend overload if many songs
            for (const song of songs) {
                await musicService.addSongToPlaylist(playlist.id, song.id);
            }

            toast({
                title: "Playlist Created!",
                description: `Created "${aiResponse.suggestedName}" with ${songs.length} songs.`,
            });

            onOpenChange(false);
            setPrompt("");
            // Navigate to the new playlist
            navigate(`/playlist/${playlist.id}`);

        } catch (error) {
            console.error("AI Generation failed", error);
            toast({
                title: "Generation Failed",
                description: error.response?.data?.message || "Something went wrong while creating your magic playlist.",
                variant: "destructive"
            });
        } finally {
            setLoading(false);
            setStep("input");
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md bg-zinc-900 border-white/10 text-white">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2 text-xl font-display">
                        <Sparkles className="text-brand-pink" size={24} />
                        AI Playlist Generator
                    </DialogTitle>
                    <DialogDescription className="text-zinc-400">
                        Describe how you feel or what you want to hear, and we'll craft the perfect playlist for you.
                    </DialogDescription>
                </DialogHeader>

                <div className="py-4">
                    {step === "input" && (
                        <Textarea
                            placeholder="e.g., 'I want to feel like I'm floating in space' or 'Upbeat music for a gym workout'"
                            className="bg-zinc-800/50 border-white/10 min-h-[100px] text-lg focus:ring-brand-pink/50 resize-none"
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                        />
                    )}

                    {step === "analyzing" && (
                        <div className="flex flex-col items-center justify-center py-8 space-y-4 text-center animate-pulse">
                            <Wand2 className="w-12 h-12 text-brand-cyan animate-bounce" />
                            <p className="text-lg font-medium text-brand-gradient">Consulting usage data...</p>
                        </div>
                    )}

                    {step === "fetching" && (
                        <div className="flex flex-col items-center justify-center py-8 space-y-4 text-center">
                            <Music className="w-12 h-12 text-brand-pink animate-spin-slow" />
                            <p className="text-lg font-medium">Picking the perfect tracks...</p>
                        </div>
                    )}

                    {step === "creating" && (
                        <div className="flex flex-col items-center justify-center py-8 space-y-4 text-center">
                            <Loader2 className="w-12 h-12 text-brand-orange animate-spin" />
                            <p className="text-lg font-medium">Building your playlist "{result?.suggestedName}"...</p>
                        </div>
                    )}
                </div>

                <DialogFooter className="sm:justify-between">
                    <Button variant="ghost" onClick={() => onOpenChange(false)} disabled={loading}>
                        Cancel
                    </Button>
                    <Button
                        onClick={handleGenerate}
                        disabled={!prompt.trim() || loading}
                        className="btn-neon bg-gradient-to-r from-brand-pink to-brand-orange border-none text-white hover:opacity-90 transition-opacity"
                    >
                        {loading ? "Magic happening..." : (
                            <>
                                <Wand2 className="w-4 h-4 mr-2" />
                                Generate
                            </>
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
